### ISSUE TITLE
都说了不要分享，不要分享，分享就被封，没得玩了吧

### ISSUE THREAD

**Issue by wishcaiji** [mymoonyue/Nodes#1]
都说了不要分享，不要分享，分享就被封，没得玩了吧，
你刚分享，我这边账号直接被封了，本来一千多天时间的，现在用不了了！

**Comment by mymoonyue** [comment]
啊？你说的哪个。我没有分享啊，就是放到github方便自己Surge和QX订阅使用。我就发给了一个人，他也是在群里的，我知道这个群还是他拉的。没分享给别人啊。另外我这就去一个小仓库，都没人看的，感觉应该不会有人知道吧。

**Comment by wishcaiji** [comment]
你不知到，git都是公开的？只要账号出现，直接就被一键连的知道了，不封你封谁啊，哪个群？
